Exception Handling

Why do programs give error messages instead of following through?

We can encase code in an exception handler to detect when errors occur.

Try...except:
  Will try to execute the code in the try block, but if it fails, it will go to exceptions and try to execute the code there.

  Let's say we have a program that will try to read and write an input file.

  try:
    getfile = open("my_file", "r")
    getfile.write("File for exception handling")
  except IOError:
    print("Unable to read or open the data in this file")

  Using a try...except statement, the try statement will be executed first. If an input file is of the wrong format or cannot be read/written to for some reason, it will then execute the except statement or statements, until it finds a statement that can run and which will return an error message.

  Sometimes, we will need to add multiple except statements to try and catch all the potential errors.

Specific Try...except statements:
  You can specify the types of errors that you want the except statement to pick up, and then execute code for those errors specifically.

  # potential code before try catch
  try:
      # code to try to execute
  except (ZeroDivisionError, NameError):
      # code to execute if there is an exception of the given types

  # code that will execute if there is no exception or a one that we are handling

  A concrete example:

  a = 1
  try:
      b = int(input("Please enter a number to divide a"))
      a = a/b
      print("Success a=",a)
  except ZeroDivisionError:
      print("The number you provided cant divide 1 because it is 0")
  except ValueError:
      print("You did not provide a number")
  except:
      print("Something went wrong")

  Finally, there is the else: and finally: statements, where else executes if all other exceptions fail, and finally executes at the end of the try...except statement no matter what.

  # potential code before try catch
  try:
      # code to try to execute
  except ZeroDivisionError:
      # code to execute if there is a ZeroDivisionError
  except NameError:
      # code to execute if there is a NameError
  except:
      # code to execute if ther is any exception
  else:
      # code to execute if there is no exception
  finally:
      # code to execute at the end of the try except no matter what

  # code that will execute if there is no exception or a one that we are handling
